version: '3'
services:
    jenkins:
        image: my-jenkins
        restart: always
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - ./volumes/jenkins-data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock